name: Build and Publish NPM Module

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    uses: CodrJS/cicd/.github/workflows/node-build-artifact.yml@main
  test:
    uses: CodrJS/cicd/.github/workflows/node-test-artifact.yml@main
    needs: build
  publish-npm:
      if: github.event_name == 'release' && github.event.action == 'created'
      name: Publish to NPM
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: "20.x"
            cache: "yarn"
            registry-url: https://registry.npmjs.org
            # Defaults to the user or organization that owns the workflow file
            scope: "@dylanbulmer"
        - run: yarn
        - uses: actions/download-artifact@v3
          with:
            name: dist
            path: dist/
        - run: cd dist && yarn publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
